language: php

php:
    - 7.2
    - 7.3
    - 7.4

sudo: false

before_script:
    - curl --version
    - composer self-update
    - composer install --no-interaction --prefer-source

script:
    - mkdir -p build/logs
    - composer test

matrix:
    fast_finish: true

notifications:
    on_success: never
    on_failure: always

after_success:
    - travis_retry php vendor/bin/php-coveralls -v
