name: Testing service-buses

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Testing out
      run: composer test
