name: build
run-name: Testing and QA  service-buses

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.2']
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # https://github.com/shivammathur/setup-php (community)
    - name: Setup PHP, extensions and composer with shivammathur/setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
      env:
        update: true
        
    - name: Validate composer.json and composer.lock
      run: composer validate
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Install tools
      run: cd tools/php-cs-fixer && composer install --prefer-dist --no-progress --no-interaction && cd -

    - name: Testing out
      run: composer test
